command_timeout = 500
format = "$directory$git_branch$time$cmd_duration$character"
[line_break]
disabled = true

# [character]
# success_symbol = "[âœ](bold green) "
# error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow) "

[directory]
read_only = " ï ½"
truncation_length = 3
truncation_symbol = "~/"

[git_branch]
symbol = " ï˜ "
style = "bold blue"
format = "on [$symbol$branch ]($style) "

[time]
disabled = true
format = '[ ğŸ•™ $time ]($style) '
time_format = "%I:%M:%S %p"
utc_time_offset = "+6"
style = "bold bg:#8a15e2"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[package]
disabled = true